name: CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  test:
    name: Test (Bun)

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2

      - uses: pnpm/action-setup@v2

      - name: Install Dependencies
        run: pnpm install

      - name: Build
        run: pnpm build

      # Exclude tests that Bun is not compatible with
      - name: Test
        run: >-
          bun run --bun test run --fileParallelism=false
          --exclude **/async-context.test.ts
          --exclude **/atomic.test.ts
          --exclude **/pool-destroy.test.ts
          --exclude **/resource-limits.test.ts
          --exclude **/teardown.test.ts
          --exclude **/termination.test.ts
          --exclude **/uncaught-exception-from-handler.test.ts
          --exclude **/worker-stdio.test.ts
