name: Publish Any Commit

on: [push, pull_request]

jobs:
  publish:
    name: Publish commit
    runs-on: ubuntu-latest
    if: github.repository == 'tinylibs/tinypool'

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 22.x
        uses: actions/setup-node@v1
        with:
          node-version: 22.x

      - uses: pnpm/action-setup@v2

      - name: Install Dependencies
        run: pnpm install

      - name: Build
        run: pnpm build

      - run: pnpx pkg-pr-new publish --compact
